%% Normalise individual structural scans and electric field magnitude images produced by ROAST
% (c) Carys Evans, UCL
% carys.evans@ucl.ac.uk
% October 2019

%This script requires SPM12

%To run this script, make sure you have run your current flow models
%through ROAST. This script converts structural MRI and E-field magnitude
%images generated by ROAST from native to standard space. This is necessary
%for any group-based statistical analysis on E-field data.


%% Define file names and locations
%FILE NAMES MUST MATCH THOSE USED IN ROAST MODELS

%Define folder path where MRI scans are located 
%THIS WILL NEED TO BE CHANGED ON ANOTHER COMPUTER
root    = 'C:\Users\cevans\Desktop\Data\';

%Define individual scans being normalised (e.g. subject1.nii), excluding
%file extension '.nii'.  Scans need to be in the same folder.
subj = {'subject1',	'subject2',	'subject3',	'subject4',	'subject5',	'subject6',	'subject7',	'subject8',...
    'subject9',	'subject10',	'subject11',	'subject12',	'subject13',	'subject14',	'subject15',...
    'subject16',	'subject17',	'subject18',	'subject19',	'subject20',	'subject21',	...
    'subject23',	'subject24',	'subject25',	'subject26',	'subject27',    'subject28',    'subject29',...
    'subject30',	'subject31',	'subject32',	'subject33',	'subject34',	'subject35',	'subject36',...
    'subject37',	'subject38',	'subject39',	'subject40',	'subject41',	'subject42',	'subject43',...
    'subject44',	'subject45',	'subject46',	'subject47',	'subject48',	'subject49',	'subject50',...
    'subject51',	'subject52',	'subject53'};

%Define tag used by ROAST to identify simulation
simtag = 'CP5FC1_1mA'; 

%Define file path for Tissue Probability Map used by SPM during
%normalisation. TPM.nii is found in spm folder: spm12\tpm\TPM.nii.
%THIS WILL NEED TO BE CHANGED ON ANOTHER COMPUTER
tpm = 'C:\Users\cevans\Documents\spm12\tpm\TPM.nii';


%% Normalise each individual's structural MRI and emag (E-field magnitude) image generated by ROAST
for i = 1:length(subj)
    spm('defaults', 'FMRI');
    cd(root)
    spm_jobman('initcfg')

    matlabbatch{1}.spm.spatial.normalise.estwrite.subj.vol = {[root, sprintf('%s.nii', subj{i}),',1']};                            
    matlabbatch{1}.spm.spatial.normalise.estwrite.subj.resample = {
                                                                    [root, sprintf('%s.nii', subj{i}),',1']                 %Normalise structural MR image
                                                                    [root, sprintf('%s_%s_emag.nii', subj{i}, simtag),',1'] %Normalise emag (E-field magnitude) image
                                                                   };
    matlabbatch{1}.spm.spatial.normalise.estwrite.eoptions.biasreg = 0.0001;
    matlabbatch{1}.spm.spatial.normalise.estwrite.eoptions.biasfwhm = 60;
    matlabbatch{1}.spm.spatial.normalise.estwrite.eoptions.tpm = {tpm};     %Location of Tissue Probability Map used in SPM
    matlabbatch{1}.spm.spatial.normalise.estwrite.eoptions.affreg = 'mni';
    matlabbatch{1}.spm.spatial.normalise.estwrite.eoptions.reg = [0 0.001 0.5 0.05 0.2];
    matlabbatch{1}.spm.spatial.normalise.estwrite.eoptions.fwhm = 0;
    matlabbatch{1}.spm.spatial.normalise.estwrite.eoptions.samp = 3;
    matlabbatch{1}.spm.spatial.normalise.estwrite.woptions.bb = [-78 -112 -70
                                                                 78 76 85];
    matlabbatch{1}.spm.spatial.normalise.estwrite.woptions.vox = [1 1 1];   %Resampled to 1mm resolution. Nb: normalised images in Evans et al., 2020 are at 2x2x2mm resolution
    matlabbatch{1}.spm.spatial.normalise.estwrite.woptions.interp = 4;
    matlabbatch{1}.spm.spatial.normalise.estwrite.woptions.prefix = 'w';    %File prefix for Normalised images. Can be changed as desired 


    spm_jobman('run', matlabbatch);
end
